require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/initializers/simple_form.*'
    - app/models/appointment.rb
    - config/environments/development.rb

RSpec/RepeatedDescription:
  Exclude:
    - spec/requests/api/**/*

RSpec/ExampleLength:
  Max: 25 # 5

RSpec/MultipleExpectations:
  Max: 8 # 4

RSpec/NestedGroups:
  Max: 5

Metrics/ClassLength:
  Max: 150

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*

RSpec/Capybara:
  Exclude:
    - spec/features/**/*

Style/Lambda:
  Enabled: false
