default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: <%= ENV['RAILS_SERVICE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: rails_service_development

test:
  <<: *default
  database: rails_service_test

production:
  <<: *default
  database: rails_service_production
  username: rails_service
  password: <%= ENV['RAILS_SERVICE_DATABASE_PASSWORD'] %>
